---
version: "2.0"
endpoints:
  uniq_name_endpoint: # unique name, for example "dvpn_dimokus:", and enter this name in line 23 and 28.
    kind: ip
services:
  app:
    image:  declab/sentinel_dvpn_ssh:0.7.2
    
    env:
      - "SSH_PASS="
      - "MNEMONIC_BASE64=" # Mnemonic phrase encrypted with BASE64.
      - "MONIKER=dVPN on Akash_Network v2RAY" # Your dVPN node name.
      - "REMOTE_PORT=8585" # Remote port for are connection sentinel client service.
      - "LISTEN_PORT=3333" # V2RAY listen port
      - "IPV4_ADDRESS=" # Node static IP address ( of leases section )
      - "RPC_ADDRESS=https://rpc.sentinel.co:443"
      - "GIGABYTE_PRICES=29000000udvpn,390000ibc/A8C2D23A1E6F95DA4E48BA349667E322BD7A6C996D8A4AAE8BA72E190F3D1477,5250000ibc/ED07A3391A112B175915CD8FAF43A2DA8E4790EDE12566649D0C2F97716B8518,7000000ibc/31FEE1A2A9F9C01113F90BD0BBCCE8FD6BBB8585FAF109A2101827DD1D5B95B8,525000000ibc/B1C0DDB14F25279A2026BC8794E12B259F8BDA546A3C5132CCAEE4431CE36783"
      - "HOURLY_PRICES=4900000udvpn"
        
    expose:
      - port: 8585 # REMOTE_URL_PORT
        as: 8585
        to:
          - global: true
            ip: uniq_name_endpoint  # Name from string 3, for example "ip: dvpn_dimokus"
      - port: 3333 # LISTEN_PORT
        as: 3333 
        to:
          - global: true
            ip: uniq_name_endpoint  # Name from string 3, for example "ip: dvpn_dimokus" 
      - port: 22 # SSH port
        to:
          - global: true   
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 1
        memory:
          size: 1Gi
        storage:
          size: 10Gi         
  placement:
    akash: 
      pricing:
        app:
          denom: uakt
          amount: 100000
deployment:
  app:
    akash:
      profile: app
      count: 1
